(function(){
const css=`.account-modal{position:fixed;inset:0;background:#0008;display:none;align-items:flex-end;justify-content:center;z-index:100}.account-modal.open{display:flex}.account-sheet{width:min(520px,100%);background:#fff;border-radius:24px 24px 0 0;padding:22px;max-height:88vh;overflow:auto}.account-sheet h2{margin-top:0}.account-sheet input{width:100%;padding:12px;border:1px solid #d9e7e1;border-radius:11px;margin:6px 0 12px}.account-sheet label{font-size:12px;font-weight:800}.account-tabs{display:flex;gap:8px;margin-bottom:15px}.account-tabs button{flex:1;padding:10px;border:0;border-radius:10px;background:#edf6f1;font-weight:800}.account-tabs .active{background:#087443;color:#fff}.account-message{font-size:13px;margin:8px 0}.account-list{display:grid;gap:9px}.account-order{background:#f4faf7;border-radius:14px;padding:13px}.account-order b,.account-order span{display:block}.account-order span{font-size:12px;color:#61736c;margin-top:4px}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const modal=document.createElement('div');modal.className='account-modal';modal.id='accountModal';modal.innerHTML=`<div class="account-sheet"><button id="accountClose" class="close" style="float:right">×</button><h2>👤 My Account</h2><div class="account-tabs"><button id="loginMode" class="active">Login</button><button id="signupMode">Create Account</button></div><div id="accountMsg" class="account-message"></div><form id="loginForm"><label>Email</label><input id="accEmail" type="email" required><label>Password</label><input id="accPassword" type="password" required><button class="primary full" type="submit">Login</button></form><form id="signupForm" hidden><label>Full Name</label><input id="accName" required><label>Mobile Number</label><input id="accPhone" inputmode="numeric" maxlength="10" pattern="[0-9]{10}" required><label>Email</label><input id="accSignupEmail" type="email" required><label>Password</label><input id="accSignupPassword" type="password" minlength="6" required><button class="primary full" type="submit">Create Account</button></form><div id="accountLogged" hidden><p id="accountWelcome"></p><div class="actions"><a class="primary" href="orders.html">📋 My Orders</a><button id="logoutBtn" class="secondary">Logout</button></div></div></div>`;document.body.appendChild(modal);
function msg(t){document.getElementById('accountMsg').textContent=t||''}function mode(signup){document.getElementById('loginMode').classList.toggle('active',!signup);document.getElementById('signupMode').classList.toggle('active',signup);document.getElementById('loginForm').hidden=signup;document.getElementById('signupForm').hidden=!signup;msg('')}
async function refresh(){const s=await AdityaAppAuth.session();document.getElementById('loginForm').hidden=!!s;document.getElementById('signupForm').hidden=!!s;document.getElementById('loginMode').hidden=!!s;document.getElementById('signupMode').hidden=!!s;document.getElementById('accountLogged').hidden=!s;if(s)document.getElementById('accountWelcome').textContent='Welcome, '+(s.user.user_metadata?.full_name||s.user.email)+'!'}
window.openAccount=async()=>{modal.classList.add('open');try{await refresh()}catch(e){msg(e.message)}};window.closeAccount=()=>modal.classList.remove('open');
document.getElementById('accountClose').onclick=closeAccount;document.getElementById('loginMode').onclick=()=>mode(false);document.getElementById('signupMode').onclick=()=>mode(true);document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();try{await AdityaAppAuth.login(accEmail.value.trim(),accPassword.value);msg('Login successful.');await refresh()}catch(err){msg(err.message||'Login failed.')}};document.getElementById('signupForm').onsubmit=async e=>{e.preventDefault();try{await AdityaAppAuth.signup(accName.value.trim(),accPhone.value.trim(),accSignupEmail.value.trim(),accSignupPassword.value);msg('Account created. Check your email if confirmation is required.');mode(false)}catch(err){msg(err.message||'Unable to create account.')}};document.getElementById('logoutBtn').onclick=async()=>{await AdityaAppAuth.logout();await refresh();msg('You are logged out.');};
const oldHeader=document.querySelector('.app-header');if(oldHeader){const b=document.createElement('button');b.className='secondary';b.textContent='👤 Account';b.onclick=openAccount;oldHeader.appendChild(b)}
})();
